spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/frontier
    username: frontier
    password: frontier
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
frontier:
  tracing:
    zipkin-endpoint: http://localhost:9411/api/v2/spans
aws:
  sqs:
    listener:
      max-messages: 5
      poll-timeout: 5s
